app <- fluidPage(
 tabBox(selected = "ak", id = "id", width="100%", 
    
    tabPanel(title = "Alaska", value = "ak",
             sidebarLayout(
               sidebarPanel(width=3,
                            selectInput(inputId = "akvar", label = h4("Variable"),
                                        choices = list("vessel counts" = "vesscounts",
                                                       "fishing weeks" = "fishingweeks",
                                                       "crew weeks"  = "crewweeks"),
                                        selected = "vessel counts",
                                        multiple = FALSE),
                            sliderInput(inputId = "ak.year", label = "Year",
                                        min = 2009, max=2019, step =1,
                                        value = c(2012,2019), dragRange=TRUE, sep=""),
                            conditionalPanel(condition = "input.akvar=='crewweeks'",
                                             selectInput(inputId = "ak.month", label = h4("Month"),
                                                         choices = month.list,
                                                         selected = "All Months",
                                                         multiple = TRUE)),
                            selectInput(inputId = "ak.sector", label = h4("Sector"),
                                        choices = sector.list,
                                        selected = "Total",
                                        multiple = TRUE),
                            conditionalPanel(condition = "input.akvar=='vesscounts'",
                                             selectInput(inputId = "ak.zone", label = h4("Zone"),
                                                         choices = zone.list,
                                                         selected = "All Alaska",
                                                         multiple = TRUE)),
                            conditionalPanel(condition = "input.akvar == 'vesscounts' || input.akvar == 'fishingweeks'",
                                             selectInput(inputId = "ak.target", label = h4("Species"),
                                                         choices = target.list,
                                                         selected = "All Groundfish",
                                                         multiple = TRUE)),
                            conditionalPanel(condition = "input.akvar == 'fishingweeks'",
                                             selectInput(inputId = "ak.gear", label = h4("Gear"),
                                                         choices = gear.list,
                                                         selected = "All Gear",
                                                         multiple = FALSE)),
                            conditionalPanel(condition = "input.akvar == 'fishingweeks'",
                                             selectInput(inputId = "ak.length", label = h4("Length"),
                                                         choices = length.list,
                                                         selected = "All lengths",
                                                         multiple = TRUE)),
                            HTML('<footer>
                    <a href="https://www.afsc.noaa.gov/REFM/Socioeconomics/SAFE/groundfish.php" style=\"color: #000000\"> For details see the Economic Status of the Groundfish Fisheries off Alaska, 2019.</a> </footer>'),
                            downloadButton(outputId="akeff_downloadData", "Download", style = "color: #000000")
               ),
               mainPanel(
                 tags$h3(tags$b(textOutput("ak_title"))),
                 plotOutput(outputId="ak_plt", height="auto"),
                 textOutput(outputId="ak_txt"),
                 div(style="overflow-x:scroll;", tableOutput(outputId="ak_tab")))
             )## close sidebarLayout
    ), ## close tabPanel
    tabPanel(title = "Bering Sea & Aluetian Islands", value = "bsai",
             sidebarLayout(
               #headerPanel("Ex-vessel data of the groundfish catch off Alaska, 2009-2019"),
               sidebarPanel(width=3,
                          selectInput(inputId = "bsaivar", label = h4("Variable"),
                                        choices = list("vessel counts" = "vesscounts",
                                                       "fishing weeks" = "fishingweeks",
                                                       "crew weeks"  = "crewweeks"),
                                        selected = "vessel counts",
                                        multiple = FALSE),
                          sliderInput(inputId = "bsai.year", label = "Year",
                                      min = 2009, max=2019, step =1,
                                      value = c(2012,2019), dragRange=TRUE, sep=""),
                          conditionalPanel(condition = "input.bsaivar == 'vesscounts' || input.bsaivar=='crewweeks'",
                                           selectInput(inputId = "bsai.month", label = h4("Month"),
                                                       choices = month.list,
                                                       selected = "All Months",
                                                       multiple = TRUE)),
                          selectInput(inputId = "bsai.sector", label = h4("Sector"),
                                      choices = sector.list,
                                      selected = "Total",
                                      multiple = TRUE),
                          conditionalPanel(condition = "input.bsaivar == 'fishingweeks'",
                                           selectInput(inputId = "bsai.target", label = h4("Species"),
                                                       choices = target.list,
                                                       selected = "All Groundfish",
                                                       multiple = TRUE)),
                          conditionalPanel(condition = "input.bsaivar == 'vesscounts'",
                                           selectInput(inputId = "bsai.gear1", label = h4("Gear"),
                                                       choices = gear.list,
                                                       selected = "All Gear",
                                                       multiple = TRUE)),
                          conditionalPanel(condition = "input.bsaivar == 'fishingweeks'",
                                           selectInput(inputId = "bsai.gear2", label = h4("Gear"),
                                                       choices = gear.list,
                                                       selected = "All Gear",
                                                       multiple = FALSE)),
                          conditionalPanel(condition = "input.bsaivar == 'fishingweeks'",
                                           selectInput(inputId = "bsai.length", label = h4("Length"),
                                                       choices = length.list,
                                                       selected = "All lengths",
                                                       multiple = TRUE)),
                            HTML('<footer>
                        <a href="https://www.afsc.noaa.gov/REFM/Socioeconomics/SAFE/groundfish.php" style=\"color: #000000\"> For details see the Economic Status of the Groundfish Fisheries off Alaska, 2019.</a> </footer>'),
                          downloadButton(outputId="bsaieff_downloadData", "Download", style = "color: #000000")
               ),
               mainPanel(
                 tags$h3(tags$b(textOutput("bsai_title"))),
                 plotOutput(outputId="bsai_plt", height="auto"),
                 textOutput(outputId="bsai_txt"),
                 div(style="overflow-x:scroll;", tableOutput(outputId="bsai_tab")))
             ) ## close sidebarLayout
    ), # close tabPanel
    tabPanel(title = "Gulf of Alaska", value = "goa",
             sidebarLayout(
               #headerPanel("Ex-vessel data of the groundfish catch off Alaska, 2009-2019"),
               sidebarPanel(width=3,
                            selectInput(inputId = "goavar", label = h4("Variable"),
                                        choices = list("vessel counts" = "vesscounts",
                                                       "fishing weeks" = "fishingweeks",
                                                       "crew weeks"  = "crewweeks"),
                                        selected = "vessel counts",
                                        multiple = FALSE),
                            sliderInput(inputId = "goa.year", label = "Year",
                                        min = 2009, max=2019, step =1,
                                        value = c(2012,2019), dragRange=TRUE, sep=""),
                            conditionalPanel(condition = "input.goavar == 'vesscounts' || input.goavar=='crewweeks'",
                                             selectInput(inputId = "goa.month", label = h4("Month"),
                                                         choices = month.list,
                                                         selected = "All Months",
                                                         multiple = TRUE)),
                            selectInput(inputId = "goa.sector", label = h4("Sector"),
                                        choices = sector.list,
                                        selected = "Total",
                                        multiple = TRUE),
                            conditionalPanel(condition = "input.goavar == 'fishingweeks'",
                                             selectInput(inputId = "goa.target", label = h4("Species"),
                                                         choices = target.list,
                                                         selected = "All Groundfish",
                                                         multiple = TRUE)),
                            conditionalPanel(condition = "input.goavar == 'vesscounts'",
                                             selectInput(inputId = "goa.gear1", label = h4("Gear"),
                                                         choices = gear.list,
                                                         selected = "All Gear",
                                                         multiple = TRUE)),
                            conditionalPanel(condition = "input.goavar == 'fishingweeks'",
                                             selectInput(inputId = "goa.gear2", label = h4("Gear"),
                                                         choices = gear.list,
                                                         selected = "All Gear",
                                                         multiple = FALSE)),
                            conditionalPanel(condition = "input.goavar == 'fishingweeks'",
                                             selectInput(inputId = "goa.length", label = h4("Length"),
                                                         choices = length.list,
                                                         selected = "All lengths",
                                                         multiple = TRUE)),
                            HTML('<footer>
                                 <a href="https://www.afsc.noaa.gov/REFM/Socioeconomics/SAFE/groundfish.php" style=\"color: #000000\"> For details see the Economic Status of the Groundfish Fisheries off Alaska, 2019.</a> </footer>'),
                            downloadButton(outputId="goaeff_downloadData", "Download", style = "color: #000000")
               ),
               mainPanel(
                 tags$h3(tags$b(textOutput("goa_title"))),
                 plotOutput(outputId="goa_plt", height="auto"),
                 textOutput(outputId="goa_txt"),
                 div(style="overflow-x:scroll;", tableOutput(outputId="goa_tab")))
                            ) ## close sidebarLayout
             ) # close tabPanel
) )

